### ISSUE TITLE
Show fade edges for scrollable areas

### ISSUE THREAD

**Issue by buzz** [buzz/newsdash#34]
Feedbox scroll area should fade out at the top (bottom) edge unless not fully scrolled to the bottom (top).

**Comment by buzz** [comment]
Use something similar to this:

```css
ul.feedList:after {
  position: fixed;
  width: 100%;
  content: '';
  bottom: 0px;
  height: 20px;
  z-index: 1;
  background: linear-gradient(to bottom, transparent, $bgcolor 90%);
}
```
